name: "🚀 Upload to FTP"
on:
  push:
    branches:
    - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 0

      - name: Update files on FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftpes://ftp.lunaris.com.au
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
